//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FieldDataAnalyzer
{
    using System;
    using System.Collections.Generic;
    
    public partial class final_gather_point_measurements
    {
        public int final_gather_point_measurement_id { get; set; }
        public System.DateTime measure_date { get; set; }
        public float Pexper { get; set; }
        public float Texper { get; set; }
        public Nullable<float> coef_P { get; set; }
        public Nullable<float> coef_T { get; set; }
        public Nullable<float> Pcoef { get; set; }
        public Nullable<float> Tcoef { get; set; }
        public Nullable<float> Pf { get; set; }
        public Nullable<float> Tf { get; set; }
    }
}
